### ISSUE TITLE
[Vagrant] set up LAMP stack without depending on scotch/box

### ISSUE THREAD

**Issue by dmill-bz** [spider/spider#101] opened 2015-11-22 12:43 UTC
`scotch/box` is very practical but only works with `virtualBox` it would be cool if we could have vagrant work on more than just vb (kvm, parallels, fusion, vmware, etc.)

**Comment by electricjones** [comment] 2015-12-01 04:03
I wasn't aware the `scotch/box` required `virtualBox`. All we need is a basic LAMP stack. It would be easy enough to provision, but I don't want to get bogged down in keeping all those bits and pieces updated. There are other basic boxes.

This is a list of what we need, add to it if I'm missing something:
- [ ] php 5.6
- [ ] xdebug
- [ ] An operating system (linux, maybe ubuntu)
- [x] Gremlin server (already provisioned)
- [x] OrientDB (already provisioned)
- [x] Neo4j (already provisioned)
- [ ] Composer (which will download all our dependencies and phpunit)
- [ ] Phpunit (could just be a project dependency, maybe not globally installed.

Is that it?

**Comment by smolinari** [comment] 2015-12-01 05:10
I could be wrong.....but,

from what I've been reading, it seems Vagrant works primarily with Virtualbox, so it isn't Scotchbox requiring Virtualbox, it is Vagrant that uses Virtualbox as its standard VM system. 

I found a [plugin to let Vagrant work with KVM](http://vagrant-kvm.readthedocs.org/en/latest/). 

Working with [Vagrant and VMWare seems to cost money and is also a addition to Vagrant](https://www.vagrantup.com/vmware). Fusion is a version of VMWare.

Parallels also has a [plugin for Vagrant](http://parallels.github.io/vagrant-parallels/docs/). 

So, to me, it sounds like people using anything other than Virtualbox need to enhance their Vagrant installation with some form of plugin. I would think, after the installation of the necessary plugin, any vagrant file offered should then build the VM with the different VM system.

It would be also cool, if the box offered a .ppk file automatically for accessing the VM via SSH and SCP. [Always recreating the .ppk key is a PITA](http://www.alittleofboth.com/2014/04/putty-unable-to-use-vagrants-private-key/). I haven't found out how to automate the creation of the .ppk file yet. Not sure it is possible. Can we maybe have a simple password setup and just tell people they are responsible for the VM's security?

And, it would be cool, if the vagrant user had direct access to the file system via SCP. I am not sure how to change permissions so this is possible. I am lazy and I like using WinSCP/SFTP to edit files on the server directly. Also, I use SFTP to sync files with my IDE. 

The first three check boxes are also given in the current box, and can be checked, right? :smile:

:+1: to the automatic installation of composer and phpunit too!

These suggestions also sound like some things I can try to learn and tackle myself. :smile: 

Scott

**Comment by smolinari** [comment] 2015-12-01 05:19
So, I think this is the key to the private key issue.

http://stackoverflow.com/questions/22922891/vagrant-ssh-authentication-failure

The trick is to tell vagrant to use a preset key, instead of vagrant making its own. 

Why didn't I think of that? LOL! :smile: 

Scott

**Comment by smolinari** [comment] 2015-12-01 06:56
Hmm..a bit contrary to what I said above, there might be a way to have the vagrant file "preset" for different VM systems. I am looking into that. Though, that means there would need to be some sort of VM system selection logic in the vagrant file too, if it should work with multiple systems. Not sure how that could work. Maybe just offer different vagrant files, Virtualbox being standard and the other files have additions to the name, like "Vagrantfile_KVM", "Vagrantfile_VMWare" and "Vagrantfile_Parallels" and requesting the users to rename the files accordingly.

I also found out a solution to my problem of not getting access to files with the vagrant user. It seems, there is a simple setting to change in WinSCP to allow sudo access from the start. 

Scott

**Comment by smolinari** [comment] 2015-12-01 07:19
Interesting. This box has flags you can add to vagrant up, to change the VM system (provider).

https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64

Looking a bit further into that, adding other providers isn't trivial. Hmm.....

Scott

**Comment by smolinari** [comment] 2015-12-01 08:07
Ok. Silly me. The password for vagrant is.....vagrant. So, I can also get into the box without the need of a private key. 

Scott

**Comment by smolinari** [comment] 2015-12-01 08:17
Cool, I didn't realise you can actually share access to the vagrant box with someone else too. 

https://atlas.hashicorp.com/help/vagrant/shares

That could have made the troubleshooting over the weekend a bit easier Dylan. :wink: But then, there are other ways to "share" too, like TeamViewer. :smile: Still, making mistakes and finding out how to fix them helps with the learning process. It just takes a lot longer. (at least with me it does)

Scott

**Comment by dmill-bz** [comment] 2015-12-01 08:23
> So, to me, it sounds like people using anything other than Virtualbox need to enhance their Vagrant installation with some form of plugin. I would think, after the installation of the necessary plugin, any vagrant file offered should then build the VM with the different VM system.

This is also what I thought but the box in question is telling me to bugger off because I'm using parallels. :(  makes me sad.

**Comment by smolinari** [comment] 2015-12-01 08:38
Hehe...yeah. I am learning the box needs to be repackaged to work with Parallels too. When it is done, then I believe you can do `vagrant up --provider=parallels` (or something similar) and it should work.

Scott

**Comment by electricjones** [comment] 2015-12-01 21:33
I think the fact that `scotchbox` doesn't work with parallels may be something to take up with the scotchbox vendor. In theory, all boxes should work with all providers, as the vagrant plugin system simply provides a common wrapper for different providers.

Everything in the checkbox list is covered by current box. The current box also provides a LOT more that we just don't need, but doesn't hurt. I really don't want to be responsible for building and distributing a brand new box. It's just overkill since all we need is phpunit.

I really feel the vagrant for spider should only have the goal of making it easy to `phpunit` test Spider itself. Nothing more. Nothing less. If anyone wants to do more, they are free to do whatever they like :)

**Comment by smolinari** [comment] 2015-12-02 06:14
@PommeVerte - bad news. https://github.com/scotch-io/scotch-box/issues/64

I'm working on a new box with Puphpet. I have it partially finished and it should allow VM creation in Parallels, VMWare and KVM too. Maybe this evening, at the latest tomorrow morning I'll have it finished.  

Scott

**Comment by dmill-bz** [comment] 2015-12-02 21:09
> I think the fact that scotchbox doesn't work with parallels may be something to take up with the scotchbox vendor. In theory, all boxes should work with all providers, as the vagrant plugin system simply provides a common wrapper for different providers.

Yeah, but he's been pretty open about not wanting to do anything for support of other providers unfortunately.

@smolinari That's awesome!! can't wait.

**Comment by dmill-bz** [comment] 2015-12-02 21:10
durh didn't see the link.

**Comment by electricjones** [comment] 2015-12-02 21:20
Well, that's a bummer. But I agree, if `scotchbox` won't support anything except virtual box, we need to switch. We can switch to another base box, but as I look through the [catalog](https://atlas.hashicorp.com/boxes/), there don't seem to be any boxes that support every provider. My guess is that the official `ubuntu/trusty64` or the default `hashicorp/precise32` would be our best bets. It would be easy enough to add php to our provisioning and run `composer update` to install phpunit and such.

I really have no desire to create our own box. That's just adding another layer of responsibility and it seems to be a community issue. I'm surprised I haven't heard more complaints about this sort of thing.

**Comment by smolinari** [comment] 2015-12-02 21:40
The Vagrant box I am working on (using puphpet/ubuntu box) is almost finished and looking good. Testing is sloooooowwwww thooouuuughhhhh.......

Scott

**Comment by electricjones** [comment] 2015-12-02 21:43
Are you willing to keep up with all the updates and testing? Every time a part of the box (php, ubuntu, etc.) has an update, the maintainer would have to update the box and make sure there were no conflicts. Plus we would have to support the box for any errors on weird systems or breakages. I'm just saying that I don't have the time to commit to that as part of the Spider project. I'd rather use a community box. However, if its easy enough and you want to keep up with that, I'm game to try it :)

I've never built a box. Not sure what all goes into it. I just know that everything is always more complicated then it should be.

**Comment by smolinari** [comment] 2015-12-02 21:58
The puphpet box should be updated automatically. I/ we would only have to keep up the vagrant side (like if we started supporting only PHP7, we'd have to change the config so the Vagrantfile  installs PHP7). 

https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64

As you can see, it has more providers too. ( not sure where KVM is though. Might have been mistaken on that one.)

My tests just ran through and worked and everything is in, as listed above. You just log in, go to the spider directory and run phpunit. I am amazed at myself that it all actually works. You can also access the two studios for ODB and Neo4j. It even has a prebuilt .ppk file for logging in from Windows! :+1: 

I'm heading to bed now though. I'll load up the Vagrant stuff in a repo tomorrow and make up some docs for its usage. Then you all can play with it. 

I am thinking the "spider-box" (as I have dubbed it) should be in its own repo, no? Like "spider/spider-box"? :smile: 

Scott

**Comment by electricjones** [comment] 2015-12-02 22:57
Why don't you put together a PR against develop using your box and add some documentation (either in /docs/ or in the issue) about what it would take to keep this up to date. A repo `spider-vagrant-box` would be fine with me.

And good night :) It's like 4pm here, lol.

**Comment by smolinari** [comment] 2015-12-03 06:40
So, here you go!

https://github.com/SkooppaOS/spider-box

I hope it works as I think it should for you Dylan. :smile: 

One note. spider-box installs phpunit and composer globally. Not sure if that is important or not, but I figured, if the user wants to do other projects, they'd have both ready and waiting. 

Scott

**Comment by electricjones** [comment] 2015-12-03 14:18
Okay, this looks great. You say it will be updated automatically when something like Ubuntu comes out with a new version? I will have to test it later when I have better internet. 

Can you do a pull request against the `develop` branch with a modified `Vagrantfile` that uses this box? That's the best way to test it.

@PommeVerte could you test it as well? If all works out and it won't be too much to maintain, I'm fine pulling this over to spider's repo, so song as @smolinari wants to transfer it.

**Comment by smolinari** [comment] 2015-12-03 14:35
Yes, the Puphpet box is updated with any new Ubuntu versions. We only have to set config values on the Vagrant side, should we want to change anything in the box itself (like the installed PHP version). 

The goal for me was to have spider-box be a part of Spider development. A tool. An assistant. As such, I'm still wondering if it shouldn't be in its own repo. In its own repo, if we make changes to spider-box, it won't bother the releases/ versions/ PRs of Spider. spider-box loads the spider develop branch itself, from which the dev can also start to use to develop with. Also, with spider-box in its own repo, it wouldn't dilute the Spider library with files it really doesn't need to run (i.e. the files under `/vagrant`and the `Vangrantfile` file itself).

Scott

**Comment by electricjones** [comment] 2015-12-03 14:39
Spider-box would be under its own repo (`spider/vagrant-box`), but `spider/spider` would still need a `Vagrantfile` that uses the new box. The idea is that one simply clone `spider/spider` and run `vagrant up` (assuming vagrant is installed).

Also, does this box install all the correct database versions, or would they still be provisioned in the `Vagrantfile`?

**Comment by dmill-bz** [comment] 2015-12-03 14:50
This looks good. I'm not really sure how it all works so just want to run a
couple of scenarios past you guys to make sure none of these end up being
blocking:
- spider 2.0 integrates new features based around some new php version..
  say it only supports php7+ but 1.x branch is still maintained. Is having
  the separate box going to be an issue here?
- same as above but lets say we deprecate orient db 2.x to only support
  orient 3+

**Comment by electricjones** [comment] 2015-12-03 14:58
Those are really good points. And I think that's the point of vagrant. You can reproduce the environment in a version-controlled way that sits right along side your code. Every release/branch/commit has a `Vagrantfile` that is perfectly suited to work with the repo at that point.

I'm warming up to the idea of maintaining a `spider/vagrant-box`, but I think each version/branch of spider should have its own `Vagrantfile` which would provision what is needed for that specific release/branch/whatever.

So, the box would really only hold the infrastructure that spider **doesn't** depend on: the operating system (and that's it?). We probably should provision
- [ ] php (minimum version supported by Spider)
- [x] xdebug
- [ ] phpunit
- [ ] composer
- [x] and the databases that are supported.

**Comment by smolinari** [comment] 2015-12-03 15:00
Ooh..ooh...ooh.....please let it be called `spider/spider-box`. Pretty please! It is already branded that way too. :smile: 

If the aim is to have the dev first clone the Spider repo, then vagrant up the box, then I need to remove the automatic cloning of the Spider repo in the box. 

> - spider 2.0 integrates new features based around some new php version..
>   say it only supports php7+ but 1.x branch is still maintained. Is having
>   the separate box going to be an issue here?
> - same as above but lets say we deprecate orient db 2.x to only support
>   orient 3+

Hmm.....the box versions can follow Spider's versions.

Scott

**Comment by electricjones** [comment] 2015-12-03 15:32
Totally fine calling it `spider/box` and the aim is that the dev only clones `spider/spider`. That's it. Vagrant will download and install the box automatically from the `Vagrantfile` in the spider repo.

This is going to be a long post because I feel like we are going in various directions and need to lay it all out to make a solid decision. So these are our options with pros and cons.

Really what it comes down to is this. In order to support multiple versions (say a dev working on Spider 1 that needs php 5.6 and another dev working on Spider 2 that needs php 7), we need multiple environments tied to the version they are working with.

There are two options, that I can see.
1. The Box is King
   - Have a repo called `spider/spider-box` with different versions (tags) of a fully built box that included everything needed (os, php, databases, etc). This box would work with as many providers as possible (virtualbox, parallels, etc)
   - Then, the `Vagrantfile` for `spider/spider` would do very little more than load the `spider/spider-box` from the correct tag. I'm not sure how to do this, or if its possible, but I'd imagine it is. A place to start would be https://docs.vagrantup.com/v2/boxes/versioning.html
   - In essence then the Vagrantfile for Spider would would load `spider/spiderbox.git#1` and the Vagrantfile for Spider 2 would load `spider/spiderbox.git#2`
2. The Vagrantfile is King
   - Here, the Vagrantfile that lives in the Spider repo is what installs all the required dependencies (php, xdbug, databases, etc).
   - The box really just holds the operating system and what is needed for a box (ssh, etc)
   - Then, we update the provisioning inside the spider repo with each version/branch of spider.
   - This is the way its setup now. The only difference is that we would add php, phpunit, and composer to the provisioning file and switch out `scotch/box` for a box that works across more providers and just has the basics needed (os).

**Thoughts**
There are pros and cons to each. 

The first approach may be easier to provision (idk) because we can use puphet which Scott seems to have a handle on. It also may _seem_ simpler to the dev because when they `vagrant up` all they see is the standard vagrant startup, not a ton of provisioning. It may also be easier to handle conflicts within the provisioning and provisioning across lots of systems. I honestly don't know, but that would make sense to me.

The con of this approach would be having to create a new box for every branch/version/tag that needs a different environment. We would have to create a new release/tag for `spider/spider-box` and then make sure that the Vagrantfile points to the correct box. Also, if a dev is working on something that requires them to change the environment (say they are initiating Spider 2 and want to use php 7), then they **must** create a new box and update `spider-box` as well as the work on the main spider repo. This requires them to have access to both, understand both, and do both correctly. I would imagine more devs are comfortable with BASH then Puphet, but I don't know. Also, the spider-box repo may get kinda big. Overall, I see this potentially adding a lot of complexity.

The second approach follows a more standard vagrant workflow. That's the way that most of the community does it (and they mostly use `homestead` or `scotchbox` or whatever. From what I've seen. It would also allow us to keep the vagrant provisioning and Travis building together. We can (and should) use the same Bash files as much as possible. That way a new change is only made in one place and everything trickles across. This approach also makes it easier (in my opinion) to make updates to the environment alongside your code. I like keeping everything in my IDE and side by side with eachother. We already keep Travis and Composer here, the environment seems a good fit as well. It would also mean less room for error in trying to match up a branch in spider with the correct branch in spider-box.

However, the second approach does mean using BASH if you are changing the environment. Really only a core dev would be doing this and its not so difficult, but it is another thing to know. 

It also (since it provisions in pieces) has some potential for errors and bugs. Its not as ATOMIC. Say the user is `vagrant up`ing, but the Gremlin Server website is down. The provisioning doesn't stop. It just doesn't install Gremlin Server right. This will lead to failed tests and a mess later. The first option is an all-or-nothing kind of option. Either the box installs or it doesn't and the user knows exactly what happens. A prebuilt box also relies on less websites (really just github and puphet) instead of each site for each piece of software (php, oracle, neo4j, etc).

This SO question (http://stackoverflow.com/questions/12582303/vagrant-box-within-git-repository) seems to recommend using the vagrant file to provision. That seems to be the most common community practice, and (truthfully) that is what I would feel most comfortable with.

The box is good work Scott, I just think it may be overkill as it is for this project.

Also, I found a list of basic boxes that are supposed to work with multiple providers:
https://atlas.hashicorp.com/bento

So, now, I'm going to let this sit for a bit so everyone can digest these options and we can continue the discussion.

In the end, the dev needs to think as little about this as possible. It should be super simple and just work from `vagrant up`, that is (after all) the point of vagrant :smile:

**Comment by smolinari** [comment] 2015-12-03 16:48
The Puphpet Vagrant setup is only subtly different to what the Scotch-box Vagrant setup was doing. The only thing missing in the Puphpet Vagrant setup was firewall rules to allow external access to the databases for the web clients and curl (and curl is most definitely configurable through Puphpet's config, I just added it in the bootstrap bash file, instead of looking for the right config change. Lazy me.) So the bash files are pretty much still the same. I moved some of the commands to the bootstrap.sh, in order to speed up the startup of an existing spider-box. 

Pretty much everything else is also configurable through the Puphpet Vagrant config (config.yaml). For instance, it is very easy to change the config, so vagrant will install the box with PHP7 and not PHP5.6. It is also very easy to install Redis or MySQL, etc. 

I also believe we wanted to test and support the latest two database versions. This can only be done with different spider-box versions/ branches with different config/ bash files. I'd not want to have keep up different boxes for these differences. 

**Ease of use for the dev.** 

I've forgotten an important step in all this. The fork. So, having spider-box clone the spider/spider repo isn't really right to begin with. So, I'll take out the cloning bit. But, I see the process like this.
- Download spider-box. `vagrant up` it.
- Fork Spider. Clone the fork locally in the spider-box shared directory.
- Or, SFTP into the box and upload it. 

A connection for IDEs can be made through the shared directory or through SFTP. 

This is also how Laravel handles their homestead box. There is no Vagrantfile in the Laravel code base.    

One thing I'd like to ask. I don't use the shared directory with Virtualbox. I SFTP into the VM. Do you guys use the shared directory? 

I can sort of understand wanting the Vagrantfile and other necessary files for the box in the Spider repo to make it even easier to download and use, but is that really the standard or necessary? I can't recall seeing Vagrantfiles in libraries I've looked at. Though, I never really paid attention to such a file. Still, I can't imagine it is the norm. I am open to be taught otherwise though.

Still, a vagrant setup to me is king, but only from a development environment standpoint. If I need different environments, I will need different vagrant setups. It is simply a tool to support the dev in setting up the dev environment and shouldn't be tied to a library. It would allow the box to be used separately from the library too. I could imagine someone interested in Graph databases wanting to use spider-box to play around with graph databases, which was one of the extra goals I had for making spider-box.

So, I am actually not for having any Vagrantfile in the Spider repo at all. Only devs working on Spider really need a spider-box. Everyone else needing Spider as a library probably won't need the spider-box, and thus they don't need those files in the Spider package. Right? :smile: 

Scott

**Comment by electricjones** [comment] 2015-12-03 20:16
Well, that was all well said and I think I was misunderstanding the workflow. I like the idea (and hadn't thought about) using spider-box for non-spider projects. There are two basic philosophies about using Vagrant and VMs. The Vanilla Vagrant approach (what vagrant was really made for) is to create a different environment for each project and have it tied to and made specifically for that project. The community has expanded into a "homestead" kind of philosophy where the environment is separate from the repo. I can see benefits to both, honestly.

So, what we are really talking about is a workflow difference, and only for those devs who want to contribute to Spider. Anyone _using_ spider would use composer or just clone.

**The Box Is king**:
1. Fork `spider/spider` to your own github account
2. Clone/download `spider/spider-box` to the local machine.
3. Run `vagrant up` to install and start the environment
4. SSH into the environment
5. Clone your fork to the shared folder, which will add it to the environment
6. Create a new branch and modify the code
7. `phpunit`
8. `git push` the branch to your fork and issue a pull request against `spider/spider`

**The Vagrantfile Is King**
1. Fork `spider/spider` to your own github account
2. Clone your fork to your local machine
3. Run `vagrant up` to install and start the environment
4. SSH into the environment
5. Create a new branch and modify the code
6. `phpunit`
7. `git push` the branch to your fork and issue a pull request against `spider/spider`

Doesn't seem to be much difference, does there?

So, the real question is, how do we keep multiple `spider/spider-box`es and how do devs know which to clone? How do they switch between different versions. This would be simple with the Vagrantfile, but I don't know how you would do it with puphet.

An example: Rui takes on the challenge of adding a feature to Spider in the Sipder-2.0 branch. He goes through steps 1-5 in the Box Is King and now has the repo ready.

However, Spider 2 (in development) requires php7 and OrientDB 3. Spider 1 (which is `master` is still with php5.6 and OrientDB 2.*. How does Rui tell the environment to load the correct box? If he needs to make changes to that box (say to add a neo4j extension or whatever), how does he do that without messing with all the other boxes?

It just seems like there will be a lot of box versions floating around out there and that could become a lot to manage as time goes on. Am I missing something?

**Comment by electricjones** [comment] 2015-12-03 20:27
And, yes, I personally use shared folders. I do like the idea of a graph database box in general.

**Comment by smolinari** [comment] 2015-12-04 06:27
I've gone ahead and removed the cloning of Spider in `spider-box`.

I've also created a second branch. "One Version Less" (couldn't come up with a better name). This would be the second supported version we mentioned. To me, that would be the only two boxes we'd need to support. It took me all of 5 minutes to make and update the "One Version Less" branch.

I'm testing and now I seem to have an issue with the loading of the puphpet box. Not sure why. Looking further. 

Scott

**Comment by smolinari** [comment] 2015-12-04 07:10
Strange, the original box works with no problems. So, something is going wrong between uploading and downloading from Github. Still testing. 

Did anyone get a spider-box running?

Edit: It definitely is an issue with Github. Very strange.

Scott

**Comment by dmill-bz** [comment] 2015-12-04 15:22
Wanted to add to this as it doesn't take into account issues with the box. It's possible that a box may be incorrectly configured but we would only realize once a particular bug shows up. How to you correct your box accross all of it's tags in this instance? 

If "vanilla" vangrant is used it is quite simple to update the version branches with a patch. seems really tedious having to do the same in a box is king setup.

Also, there's a third option not mentioned here but having a box is king strategy placed directly into the spider repo may provide a lot of pros with the only major con being that it will take some space.

Anyways, I'm not big on the idea of having a box just for spider. I know the argument is that it isn't just for spider but do we have any immediate or even medium goal projects that would require the use of this box ?

**Comment by smolinari** [comment] 2015-12-04 16:01
I'm looking into packaging boxes with packer. It seems, it is quite easy. I am just not sure what is packed together. Learning, learning. 

More later! 

Scott

**Comment by electricjones** [comment] 2015-12-04 16:12
Honestly, I would tend to agree with @PommeVerte. We haven't even gotten a working prototype yet. Splitting our goals seems like the wrong direction.

I vote for vanilla vagrant inside the repo. Its easier to version, simpler to utilize, and doesn't really take any space. We can also share Travis and Vagrant building which (to me) is a big plus.

No reason you couldn't keep and promote the box as a graph database playground, though. Would be good to have in the docs for those new to graphs. Include sample graphs, several databases, tutorials, and packages. I would have LOVED to have had something like that. And if you want to take that on, I'm happy to help where I can. It may be a good side project in the Spider repo if you felt like heading that up. Just a thought.

**Comment by smolinari** [comment] 2015-12-04 17:02
I have no goals...yet. :smile: So, I don't mind working on this. I am learning a lot. I'd like to get the box going, even if it is just to say, "I got it done!"

Scott

**Comment by electricjones** [comment] 2015-12-04 19:45
Sounds great. Most of my best learning experiences were like that, lol.

So, I'm going to start a new branch `finish-vagrant-ci` and issue a pull request, moving this and a couple other things to that. I'd really like to get this vagrant and CI thing settled so we can get back to the code :wink:

**Comment by smolinari** [comment] 2015-12-05 05:28
Well, it turns out packer isn't what I was expecting. We'd still need provisioners (the shell scripts) so, it isn't doing what I would have wanted in terms of versioning, as the shell scripts are what we'd be changing most often. And the updates of the boxes would then be in our hands too. 

So, I am going back to puphpet and trying to figure out why uploading and downloading the vagrant files to and from Github is causing a problem. 

I also now have a strange problem that Gremlin isn't installing. I am going to break down the shell scripts into separate tasks, as I can then test them separately with `vagrant provision --provision-with shell`. This would run only changed shell files to troubleshoot them and save tons of time, as going through the whole process each time is very time consuming. 

Scott

**Comment by electricjones** [comment] 2015-12-05 05:39
Alright. Just so you know, I've created a new branch to finish all this up. I am (this weekend hopefully) going to 
1. Switch out boxes for one that works with more providers
2. Provision PHP and such
3. Try to reuse as much of the shell scripts as possible between Travis and Vagrant

And, as far as I'm concerned, that should close out vagrant. Anything that you are doing that may be helpful to those three goals, let me know. This will be a vanilla vagrant, though. We are not creating a new box for this. Instead, I'm going to use a simple Ubuntu box I found that works with several providers and shell provision everything

**Comment by smolinari** [comment] 2015-12-05 07:03
Hmm....then we'd be working almost towards the same goals. :smile: I've fixed the gremlin issue. Theoretically, breaking down the shell scripts into individual tasks will make it easier to use them between vagrant and travis, I would think. 

At any rate, I am almost there. Just need some more testing. 

Scott

**Comment by smolinari** [comment] 2015-12-05 17:24
Hey Chris. Which box is it you found? I'd like to also play with it some, if I may. The puphpet box isn't making me happy. LOL!

The reason it isn't making me happy is the long build time and the fact I can't for the life of me get it to download and then work properly from Github.

Scott

**Comment by electricjones** [comment] 2015-12-06 05:58
https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64

working fine so far at least with virtualbox

**Comment by smolinari** [comment] 2015-12-06 07:32
Interesting. That is the same box I am using, just with the Puphpet stuff for Vagrant. How long does the VM take to build? It takes 15 minutes currently for the box I've got going.

Scott

**Comment by electricjones** [comment] 2015-12-06 16:14
The building doesn't take long. It's the downloading that can be a bear and I guess that depends on your internet speed. This box is smaller than scotchbox. I think it took me 5 or six (after downloading the box the first time). The box is about a gig. Also, once we get the provisioning right, you shouldn't have to rebuild the box. `vagrant suspend` will keep the box state for you and just dump it to your hardrive so it only takes a minute to `vagrant up`. `vagrant halt` will power down the machine so next time you don't have to provision, just go through the bootup.

**Comment by smolinari** [comment] 2015-12-06 18:35
Well, if I could only share the box I have somehow. I have it working and finished, but when I upload the puphpet directory and vagrantfile, then download it, I always get the same error, when I try to "vagrant up" it and nothing on the Internet helps. 

Scott

**Comment by electricjones** [comment] 2015-12-06 23:02
I really don't know anything about puphet. Do they have a support forum or something?

**Comment by smolinari** [comment] 2015-12-07 04:50
I already asked for help in a Github issue and the maker of Puphpet said he couldn't help. I am trying something else, just to see if it works. Unfortunately, it won't help having the Vagrantfile in the Spider library, since it is hosted on Github. But, I want to make sure the problem is Github specific.

Edit: the way it is looking, it is Github specific.

Edit2: This works. https://drive.google.com/file/d/0B_Iz67_Q2ImPcWE2LVA2V2lleWs/view?usp=sharing

Download, unzip, vagrant up -> working spider-box server on 192.168.33.10.

Trying also again with a new repo on Github. I hate it when a technology makes me look stupid. 

Edit3: No go. Github or the uploading or downloading of the files to or from Github somehow screws it up. Very strange....

Scott

**Comment by smolinari** [comment] 2015-12-07 07:46
I just upgraded my Virtualbox to version 5.0.10 and now the Github downloaded version is working. 

Chris, can you do me a favor and test it please?

https://github.com/SkooppaOS/spider-box

Edit: I was too fast. I think I got my downloads mixed up. The Github version still doesn't work. 

Still, if you could try it out, just to see if you also get an error something like this,

```
 INFO interface: error: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong."
```

I'd appreciate it.

Edit. And if it doesn't work, can you please try the download from Google Drive above?

Scott

**Comment by electricjones** [comment] 2015-12-07 20:52
I will have to test these Wednesday.

**Comment by smolinari** [comment] 2015-12-08 07:06
I just downloaded the ZIP version of the repo and it worked. So, it seems to be some sort of git issue on my side. I am still trying out different things to get to the bottom of this.

I also am trying the most up-to-date versions of Neo4j and Gremlin, just to see what happens. Sucks each box takes 15 minutes to build. Otherwise this could be a lot of fun too. LOL! :smile: 

Edit: I tried gremlin 3.1.0 and it breaks the tests. Going back to 3.0.2. 

Edit2: 3.0.2 works. Should I start an issue for 3.1.0 breaking?

Scott

**Comment by electricjones** [comment] 2015-12-08 14:00
I wouldn't quite yet. This isn't the box we're going to be using and I'd like to make sure its a Gremlin problem.

**Comment by electricjones** [comment] 2015-12-08 14:01
Wait, I misread that. Yes, if the upgrade breaks tests, please start an issue.

**Comment by smolinari** [comment] 2015-12-08 14:41
Ok. I am going to double check the tests with Gremlin 3.1.0 this evening just to make sure there is the issue and then report it.

The "spider-box" is almost solid now. There is only the issue, when cloning from Github. I still need to find out why that breaks the Vagrant build process and I am not sure it will work at all. It is a strange issue. 

Scott

**Comment by smolinari** [comment] 2015-12-09 08:13
Ok. I've found out my problem and of course, learned something too getting to the solution. (and although local to my Windows machine, it could happen to anyone else). It seems Git on Windows tries to be smart for the user and automatically adds CRLF to the end of lines in files it thinks it needs to add them to. This, of course, screws up files, when they are placed on a Unix machine. Thus, a simple global change in Git config fixes the issue. 

`git config --global core.autocrlf false`

Since I program mainly for Unix OSes and my IDE can work with the LF endings, I will keep this setting. 

Theoretically, I can add something to .gitattributes to enforce proper file endings too.  I need to look into that some more, so I can make sure someone else's Windows doesn't bork all the files, when they clone the repo. 

But for sure, cloning with the right setting works perfectly. So, my "spider-box" is also theoretically usable with Spider now, if you want it. :smile: I'd be interested to know, if it works on Mac now too. I might get my Mac Book Pro out of the DJ room and fire it up and see. Or maybe @PommeVerte Dylan, you can try it?

https://github.com/SkooppaOS/spider-box

Scott

**Comment by electricjones** [comment] 2015-12-09 23:43
@smolinari I wanted you to know that I also cloned spider-box and it works fine on my machine, but it takes a long time to load.

In any case, since we've decided to go with a vanilla box, I think we will stick to suggesting yours in documentation as a way to learn graph databases. If you'd like to transfer it to the organization and keep up with it as a secondary spider project, that would be cool. It may be nice to have a fully-features "spider-box" that has a range of graph dbs, some sample graph data, and maybe a tutorial or two as a way for people to learn about graph databases in general. The Vagrantfile for Spider, however, exists only to test the current implementation of spider. Let me know what you want to do.

**Comment by electricjones** [comment] 2015-12-09 23:50
Now that PR #106 is active, I'm closing this conversation to move it there.

**Closed as completed by electricjones** 2015-12-09 23:50 UTC

**Comment by smolinari** [comment] 2015-12-10 03:43
Sure, yes please do pull it into the Spider project as its own repo. I have no problem with its upkeep (as it is relatively easy and takes little time). Maybe I can figure out how to install Titan too. I don't think Titan has a GUI though.

I'll change the wording in the README:md about it being for Spider development and more for a graph database playground.

I also found out you only have to change the provider in the config.yaml file to parallels or vmware to have it run with those providers. Still need testing on that though. Hint, hint. Dylan. :smile: @PommeVerte  

And the idea to add data is a good one. OrientDB already has their Grateful Dead Concert database in it. I'll have to look at what to load for Neo4j.

Scott

**Comment by electricjones** [comment] 2015-12-10 04:19
So, the best thing to do is for you to transfer ownership of the repo to the Spider Organization. I've invited you to have Admin rights for now, so you can transfer it. Then, I will make you the admin of that repo. Once you've accepted the invite, go to "settings" and down to the bottom where it says "transfer repository"

**Comment by electricjones** [comment] 2015-12-10 04:19
Actually, scratch that. Just let me upload it. Still accept the invite so you can have access to the new repo.

**Comment by electricjones** [comment] 2015-12-10 04:32
That is done. Once you accept the invitation, you should have write access on `spider/spider-box`. Let's move all conversation to issues there :smile:

**Comment by smolinari** [comment] 2015-12-10 05:31
Roger! And thanks!

Scott
